// Theme presets for the browser harness: the --vscode-* variables the dashboard reads, with the
// values VS Code's four built-in themes give them. Taken from the colour registry and the
// theme-defaults extension of VS Code 1.140 (derived colours such as "darken(errorForeground, 0.4)"
// are written out). A variable a theme leaves undefined is absent here too - that is what the
// fallback chains in styles.css are for (e.g. no statusBarItem.errorBackground in High Contrast
// Dark, no testing.iconQueued in either high-contrast theme, no contrastBorder in Dark+ / Light+).

export interface ThemePreset {
  id: 'dark' | 'light' | 'hc-dark' | 'hc-light';
  label: string;
  /** Classes VS Code puts on <body> for this theme. */
  bodyClasses: string[];
  /** data-vscode-theme-kind on <body>. */
  kind: string;
  /** What the dashboard sits on, per host: the side bar (default), the editor area or the panel. */
  surfaces: { sideBar: string; editor: string; panel: string };
  vars: Record<string, string>;
}

/** Windows defaults; the same for every theme. */
const FONTS: Record<string, string> = {
  '--vscode-font-family': '"Segoe WPC", "Segoe UI", sans-serif',
  '--vscode-font-size': '13px',
  '--vscode-font-weight': 'normal',
  '--vscode-editor-font-family': "Consolas, 'Courier New', monospace",
  '--vscode-editor-font-size': '14px',
  '--vscode-editor-font-weight': 'normal',
};

const DARK_PLUS: ThemePreset = {
  id: 'dark',
  label: 'Dark+',
  bodyClasses: ['vscode-dark'],
  kind: 'vscode-dark',
  surfaces: { sideBar: '#252526', editor: '#1e1e1e', panel: '#1e1e1e' },
  vars: {
    ...FONTS,
    '--vscode-foreground': '#cccccc',
    '--vscode-descriptionForeground': 'rgba(204, 204, 204, 0.7)',
    '--vscode-disabledForeground': 'rgba(204, 204, 204, 0.5)',
    '--vscode-errorForeground': '#f48771',
    '--vscode-icon-foreground': '#c5c5c5',
    '--vscode-focusBorder': '#007fd4',
    '--vscode-textLink-foreground': '#3794ff',
    '--vscode-textLink-activeForeground': '#3794ff',
    '--vscode-widget-border': '#303031',
    '--vscode-sideBar-background': '#252526',
    '--vscode-sideBarSectionHeader-border': 'rgba(204, 204, 204, 0.2)',
    '--vscode-editor-background': '#1e1e1e',
    '--vscode-editor-foreground': '#d4d4d4',
    '--vscode-editorWidget-background': '#252526',
    '--vscode-button-background': '#0e639c',
    '--vscode-button-foreground': '#ffffff',
    '--vscode-button-hoverBackground': '#1177bb',
    '--vscode-button-secondaryBackground': '#2a2d2e',
    '--vscode-button-secondaryForeground': '#cccccc',
    '--vscode-button-secondaryHoverBackground': '#323637',
    '--vscode-button-secondaryBorder': 'rgba(204, 204, 204, 0.15)',
    '--vscode-dropdown-background': '#3c3c3c',
    '--vscode-dropdown-foreground': '#f0f0f0',
    '--vscode-dropdown-border': '#3c3c3c',
    '--vscode-input-background': '#3c3c3c',
    '--vscode-input-foreground': '#cccccc',
    '--vscode-checkbox-background': '#3c3c3c',
    '--vscode-checkbox-foreground': '#f0f0f0',
    '--vscode-checkbox-border': '#6b6b6b',
    '--vscode-testing-iconPassed': '#73c991',
    '--vscode-testing-iconQueued': '#cca700',
    '--vscode-testing-iconFailed': '#f88070',
    '--vscode-editorWarning-foreground': '#cca700',
    '--vscode-editorError-foreground': '#f14c4c',
    '--vscode-statusBarItem-errorBackground': '#c72e0f',
    '--vscode-statusBarItem-errorForeground': '#ffffff',
    '--vscode-statusBarItem-warningBackground': '#7a6400',
    '--vscode-statusBarItem-warningForeground': '#ffffff',
    '--vscode-inputValidation-infoBackground': '#063b49',
    '--vscode-inputValidation-infoBorder': '#007acc',
    '--vscode-inputValidation-warningBackground': '#352a05',
    '--vscode-inputValidation-warningBorder': '#b89500',
    '--vscode-inputValidation-errorBackground': '#5a1d1d',
    '--vscode-inputValidation-errorBorder': '#be1100',
    '--vscode-progressBar-background': '#0e70c0',
    '--vscode-list-hoverBackground': '#2a2d2e',
    '--vscode-badge-background': '#4d4d4d',
    '--vscode-badge-foreground': '#ffffff',
    '--vscode-scrollbarSlider-background': 'rgba(121, 121, 121, 0.4)',
  },
};

const LIGHT_PLUS: ThemePreset = {
  id: 'light',
  label: 'Light+',
  bodyClasses: ['vscode-light'],
  kind: 'vscode-light',
  surfaces: { sideBar: '#f3f3f3', editor: '#ffffff', panel: '#ffffff' },
  vars: {
    ...FONTS,
    '--vscode-foreground': '#616161',
    '--vscode-descriptionForeground': '#717171',
    '--vscode-disabledForeground': 'rgba(97, 97, 97, 0.5)',
    '--vscode-errorForeground': '#a1260d',
    '--vscode-icon-foreground': '#424242',
    '--vscode-focusBorder': '#0090f1',
    '--vscode-textLink-foreground': '#006ab1',
    '--vscode-textLink-activeForeground': '#006ab1',
    '--vscode-widget-border': '#d4d4d4',
    '--vscode-sideBar-background': '#f3f3f3',
    '--vscode-sideBarSectionHeader-border': 'rgba(97, 97, 97, 0.19)',
    '--vscode-editor-background': '#ffffff',
    '--vscode-editor-foreground': '#000000',
    '--vscode-editorWidget-background': '#f3f3f3',
    '--vscode-button-background': '#007acc',
    '--vscode-button-foreground': '#ffffff',
    '--vscode-button-hoverBackground': '#0062a3',
    '--vscode-button-secondaryBackground': '#e8e8e8',
    '--vscode-button-secondaryForeground': '#616161',
    '--vscode-button-secondaryHoverBackground': '#ffffff',
    '--vscode-button-secondaryBorder': 'rgba(97, 97, 97, 0.15)',
    '--vscode-dropdown-background': '#ffffff',
    '--vscode-dropdown-foreground': '#616161',
    '--vscode-dropdown-border': '#cecece',
    '--vscode-input-background': '#ffffff',
    '--vscode-input-foreground': '#616161',
    '--vscode-checkbox-background': '#ffffff',
    '--vscode-checkbox-foreground': '#616161',
    '--vscode-checkbox-border': '#919191',
    '--vscode-testing-iconPassed': '#73c991',
    '--vscode-testing-iconQueued': '#855f00',
    '--vscode-testing-iconFailed': '#b01011',
    '--vscode-editorWarning-foreground': '#bf8803',
    '--vscode-editorError-foreground': '#e51400',
    '--vscode-statusBarItem-errorBackground': '#c72e0f',
    '--vscode-statusBarItem-errorForeground': '#ffffff',
    '--vscode-statusBarItem-warningBackground': '#725102',
    '--vscode-statusBarItem-warningForeground': '#ffffff',
    '--vscode-inputValidation-infoBackground': '#d6ecf2',
    '--vscode-inputValidation-infoBorder': '#007acc',
    '--vscode-inputValidation-warningBackground': '#f6f5d2',
    '--vscode-inputValidation-warningBorder': '#b89500',
    '--vscode-inputValidation-errorBackground': '#f2dede',
    '--vscode-inputValidation-errorBorder': '#be1100',
    '--vscode-progressBar-background': '#0e70c0',
    '--vscode-list-hoverBackground': '#e8e8e8',
    '--vscode-badge-background': '#c4c4c4',
    '--vscode-badge-foreground': '#333333',
    '--vscode-scrollbarSlider-background': 'rgba(100, 100, 100, 0.4)',
  },
};

const HC_DARK: ThemePreset = {
  id: 'hc-dark',
  label: 'High Contrast Dark',
  bodyClasses: ['vscode-high-contrast'],
  kind: 'vscode-high-contrast',
  surfaces: { sideBar: '#000000', editor: '#000000', panel: '#000000' },
  vars: {
    ...FONTS,
    '--vscode-foreground': '#ffffff',
    '--vscode-descriptionForeground': 'rgba(255, 255, 255, 0.7)',
    '--vscode-disabledForeground': '#a5a5a5',
    '--vscode-errorForeground': '#f48771',
    '--vscode-icon-foreground': '#ffffff',
    '--vscode-focusBorder': '#f38518',
    '--vscode-contrastBorder': '#6fc3df',
    '--vscode-contrastActiveBorder': '#f38518',
    '--vscode-textLink-foreground': '#21a6ff',
    '--vscode-textLink-activeForeground': '#21a6ff',
    '--vscode-widget-border': '#6fc3df',
    '--vscode-sideBar-background': '#000000',
    '--vscode-sideBarSectionHeader-border': '#6fc3df',
    '--vscode-editor-background': '#000000',
    '--vscode-editor-foreground': '#ffffff',
    '--vscode-editorWidget-background': '#0c141f',
    '--vscode-button-background': '#000000',
    '--vscode-button-foreground': '#ffffff',
    '--vscode-button-hoverBackground': '#000000',
    '--vscode-button-border': '#6fc3df',
    '--vscode-button-secondaryForeground': '#ffffff',
    '--vscode-button-secondaryBorder': '#6fc3df',
    '--vscode-dropdown-background': '#000000',
    '--vscode-dropdown-foreground': '#ffffff',
    '--vscode-dropdown-border': '#6fc3df',
    '--vscode-input-background': '#000000',
    '--vscode-input-foreground': '#ffffff',
    '--vscode-input-border': '#6fc3df',
    '--vscode-checkbox-background': '#000000',
    '--vscode-checkbox-foreground': '#ffffff',
    '--vscode-checkbox-border': '#6fc3df',
    '--vscode-testing-iconPassed': '#73c991',
    '--vscode-editorWarning-foreground': '#ffd370',
    '--vscode-editorError-foreground': '#f48771',
    '--vscode-statusBarItem-errorForeground': '#ffffff',
    '--vscode-statusBarItem-warningForeground': '#ffffff',
    '--vscode-inputValidation-infoBackground': '#000000',
    '--vscode-inputValidation-infoBorder': '#6fc3df',
    '--vscode-inputValidation-warningBackground': '#000000',
    '--vscode-inputValidation-warningBorder': '#6fc3df',
    '--vscode-inputValidation-errorBackground': '#000000',
    '--vscode-inputValidation-errorBorder': '#6fc3df',
    '--vscode-progressBar-background': '#6fc3df',
    '--vscode-list-hoverBackground': 'rgba(255, 255, 255, 0.1)',
    '--vscode-badge-background': '#000000',
    '--vscode-badge-foreground': '#ffffff',
    '--vscode-scrollbarSlider-background': 'rgba(111, 195, 223, 0.6)',
  },
};

const HC_LIGHT: ThemePreset = {
  id: 'hc-light',
  label: 'High Contrast Light',
  // VS Code adds the plain high-contrast class as well, so rules for it cover both themes.
  bodyClasses: ['vscode-high-contrast-light', 'vscode-high-contrast'],
  kind: 'vscode-high-contrast-light',
  surfaces: { sideBar: '#ffffff', editor: '#ffffff', panel: '#ffffff' },
  vars: {
    ...FONTS,
    '--vscode-foreground': '#292929',
    '--vscode-descriptionForeground': 'rgba(41, 41, 41, 0.7)',
    '--vscode-disabledForeground': '#7f7f7f',
    '--vscode-errorForeground': '#b5200d',
    '--vscode-icon-foreground': '#292929',
    '--vscode-focusBorder': '#006bbd',
    '--vscode-contrastBorder': '#0f4a85',
    '--vscode-contrastActiveBorder': '#006bbd',
    '--vscode-textLink-foreground': '#0f4a85',
    '--vscode-textLink-activeForeground': '#0f4a85',
    '--vscode-widget-border': '#0f4a85',
    '--vscode-sideBar-background': '#ffffff',
    '--vscode-sideBarSectionHeader-border': '#0f4a85',
    '--vscode-editor-background': '#ffffff',
    '--vscode-editor-foreground': '#292929',
    '--vscode-editorWidget-background': '#ffffff',
    '--vscode-button-background': '#0f4a85',
    '--vscode-button-foreground': '#ffffff',
    '--vscode-button-hoverBackground': '#0f4a85',
    '--vscode-button-border': '#0f4a85',
    '--vscode-button-secondaryBackground': '#ffffff',
    '--vscode-button-secondaryForeground': '#292929',
    '--vscode-button-secondaryBorder': '#0f4a85',
    '--vscode-dropdown-background': '#ffffff',
    '--vscode-dropdown-foreground': '#292929',
    '--vscode-dropdown-border': '#0f4a85',
    '--vscode-input-background': '#ffffff',
    '--vscode-input-foreground': '#292929',
    '--vscode-input-border': '#0f4a85',
    '--vscode-checkbox-background': '#ffffff',
    '--vscode-checkbox-foreground': '#292929',
    '--vscode-checkbox-border': '#0f4a85',
    '--vscode-testing-iconPassed': '#007100',
    '--vscode-editorWarning-foreground': '#895503',
    '--vscode-editorError-foreground': '#b5200d',
    '--vscode-statusBarItem-errorBackground': '#b5200d',
    '--vscode-statusBarItem-errorForeground': '#ffffff',
    '--vscode-statusBarItem-warningBackground': '#895503',
    '--vscode-statusBarItem-warningForeground': '#ffffff',
    '--vscode-inputValidation-infoBackground': '#ffffff',
    '--vscode-inputValidation-infoBorder': '#0f4a85',
    '--vscode-inputValidation-infoForeground': '#292929',
    '--vscode-inputValidation-warningBackground': '#ffffff',
    '--vscode-inputValidation-warningBorder': '#0f4a85',
    '--vscode-inputValidation-warningForeground': '#292929',
    '--vscode-inputValidation-errorBackground': '#ffffff',
    '--vscode-inputValidation-errorBorder': '#0f4a85',
    '--vscode-inputValidation-errorForeground': '#292929',
    '--vscode-progressBar-background': '#0f4a85',
    '--vscode-list-hoverBackground': 'rgba(15, 74, 133, 0.1)',
    '--vscode-badge-background': '#0f4a85',
    '--vscode-badge-foreground': '#ffffff',
    '--vscode-scrollbarSlider-background': 'rgba(15, 74, 133, 0.4)',
  },
};

export const THEMES: readonly ThemePreset[] = [DARK_PLUS, LIGHT_PLUS, HC_DARK, HC_LIGHT];

export function themeById(id: string | null): ThemePreset {
  return THEMES.find((theme) => theme.id === id) ?? DARK_PLUS;
}
