import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { TurnCache, readTurn, readTurnReading } from '../../src/core/transcript';
import type { TurnActivity } from '../../src/core/types';
import {
  assistant,
  createFixtureDir,
  jsonl,
  noise,
  prompt,
  textBlock,
  toolResult,
  toolUse,
  wakeupCall,
  type FixtureDir,
  type Json,
} from './fixtures';

// Shapes as Claude Code 2.1.289 writes them (seen in its source): the Esc marker is a one-block
// array, a local command run from the VS Code panel is a caveat (isMeta), the command and its
// output, and a declined permission is a tool_result marked toolDenialEndsTurn.

const MAIN = { mainThread: true };
const AT = (time: string): string => `2026-01-31T${time}Z`;
const ms = (time: string): number => Date.parse(AT(time));

function user(content: unknown, time: string, extra: Json = {}): Json {
  return { type: 'user', timestamp: AT(time), message: { role: 'user', content }, ...extra };
}

const marker = (time = '12:40:00.000', text = '[Request interrupted by user]'): Json => user([textBlock(text)], time);
const caveat = (time = '12:40:00.000'): Json =>
  user('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>', time, {
    isMeta: true,
  });
const commandName = (time = '12:40:00.100'): Json =>
  user('<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>', time);
const stdout = (time = '12:40:00.200', tag = 'local-command-stdout'): Json => user(`<${tag}>Set model to Opus</${tag}>`, time);
const denial = (extra: Json = { toolDenialEndsTurn: true }): Json =>
  toolResult("The user doesn't want to proceed with this tool use. The tool use was rejected.", { ...extra });
const modelCommand = (start = 0): Json[] => [
  caveat(`12:4${start}:00.000`),
  commandName(`12:4${start}:00.100`),
  stdout(`12:4${start}:00.200`),
];

let fx: FixtureDir;

beforeAll(() => {
  fx = createFixtureDir();
});

afterAll(() => {
  fx.remove();
});

const reading = (records: readonly unknown[], options = MAIN) => readTurnReading(fx.transcript(records), options);
const turnOf = async (records: readonly unknown[], options = MAIN) => (await reading(records, options)).turn;

describe('main thread: how a turn ends besides end_turn', () => {
  it('the Esc marker closes it', async () => {
    const records = [prompt('go'), assistant('tool_use', [toolUse('Bash', { command: 'npm test' })]), marker()];
    expect(await turnOf(records)).toMatchObject({ state: 'CLOSED', reason: 'interrupted' });
    const forTool = [prompt('go'), marker('12:40:00.000', '[Request interrupted by user for tool use]')];
    expect(await turnOf(forTool)).toMatchObject({ state: 'CLOSED', reason: 'interrupted' });
  });

  it('a declined permission that ends the turn closes it', async () => {
    const records = [prompt('go'), assistant('tool_use', [toolUse('Bash', { command: 'rm -rf build' })]), denial()];
    expect(await turnOf(records)).toMatchObject({ state: 'CLOSED', reason: 'toolDeclined' });
  });

  it('the output of a local command closes it, and so does its stderr', async () => {
    expect(await turnOf([prompt('go'), assistant('end_turn'), ...modelCommand()])).toMatchObject({
      state: 'CLOSED',
      reason: 'localCommand',
    });
    expect(await turnOf([stdout('12:40:00.200', 'local-command-stderr')])).toMatchObject({ reason: 'localCommand' });
    expect(await turnOf([user([textBlock('<local-command-stdout>ok</local-command-stdout>')], '12:40:00.000')])).toMatchObject({
      reason: 'localCommand',
    });
  });

  it('skips the caveat in front of a local command', async () => {
    expect(await turnOf([prompt('go'), assistant('end_turn'), caveat()])).toMatchObject({ state: 'CLOSED', reason: 'turnEnded' });
    expect(await turnOf([prompt('go'), assistant('tool_use'), caveat()])).toMatchObject({ state: 'OPEN', reason: 'toolInFlight' });
  });
});

describe('near misses stay open', () => {
  it('a typed prompt that reads like the marker (prompts are plain strings)', async () => {
    expect(await turnOf([prompt('go'), assistant('end_turn'), prompt('[Request interrupted by user]')])).toMatchObject({
      state: 'OPEN',
      reason: 'thinking',
    });
  });

  it('a marker with anything added, or a different text', async () => {
    for (const content of [
      [textBlock('[Request interrupted by user]'), textBlock('and more')],
      [textBlock('[Request interrupted by user] ')],
      [textBlock('[request interrupted by user]')],
      [{ type: 'text', text: ['[Request interrupted by user]'] }],
      [toolUse('Bash', {})],
    ]) {
      expect((await turnOf([prompt('go'), user(content, '12:40:00.000')])).state, JSON.stringify(content)).toBe('OPEN');
    }
  });

  it('a denial that is not marked as ending the turn, or is not a tool answer', async () => {
    for (const extra of [{}, { toolDenialEndsTurn: 'true' }, { toolDenialEndsTurn: 1 }, { toolDenialEndsTurn: false }]) {
      expect(await turnOf([prompt('go'), denial(extra)]), JSON.stringify(extra)).toMatchObject({ reason: 'readingToolResult' });
    }
    expect(await turnOf([prompt('go'), user('no', '12:40:00.000', { toolDenialEndsTurn: true })])).toMatchObject({
      state: 'OPEN',
      reason: 'thinking',
    });
  });

  it('a bare command record: a prompt command may be about to run', async () => {
    expect(await turnOf([prompt('go'), assistant('end_turn'), commandName()])).toMatchObject({ state: 'OPEN', reason: 'thinking' });
  });

  it('a compact summary that mentions command output is still a compaction', async () => {
    const summary = prompt('<local-command-stdout>old output</local-command-stdout>', { isCompactSummary: true });
    expect(await turnOf([summary])).toMatchObject({ state: 'OPEN', reason: 'compacting' });
  });

  it("a subagent's own file closes only with end_turn: a parked agent may resume", async () => {
    const records = [prompt('review a'), assistant('tool_use'), marker()];
    expect(await turnOf(records, { mainThread: false })).toMatchObject({ state: 'OPEN', reason: 'thinking' });
    expect(await readTurn(fx.transcript([prompt('go'), denial()]))).toMatchObject({ reason: 'readingToolResult' });
    expect(await readTurn(fx.transcript([prompt('go'), stdout()]))).toMatchObject({ reason: 'thinking' });
  });

  it("a subagent's marker inside the main transcript does not close the main turn", async () => {
    const records = [prompt('go'), assistant('end_turn'), { ...marker(), isSidechain: true }];
    expect(await turnOf(records)).toMatchObject({ state: 'OPEN', reason: 'thinking' });
  });
});

describe('activity: the newest record only a turn writes', () => {
  const activity = async (records: readonly unknown[], options = MAIN): Promise<TurnActivity> =>
    (await reading(records, options)).activity;

  it('is the reply that ended the turn, not the local command after it', async () => {
    expect(await activity([prompt('go'), assistant('end_turn'), ...modelCommand()])).toEqual({ kind: 'at', ms: ms('12:34:56.789') });
  });

  it('is the prompt that opened a new turn', async () => {
    expect(await activity([prompt('go'), assistant('end_turn'), user('next please', '12:50:00.000')])).toEqual({
      kind: 'at',
      ms: ms('12:50:00.000'),
    });
  });

  it('looks past the Esc marker, a declined tool and `!` lines', async () => {
    const records = [
      prompt('go'),
      assistant('tool_use', [toolUse('Bash', {})]),
      marker('12:41:00.000'),
      denial(),
      user('<bash-input>ls</bash-input>', '12:42:00.000'),
      user('<bash-stdout>a b</bash-stdout><bash-stderr></bash-stderr>', '12:42:00.100'),
      noise('system'),
    ];
    expect(await activity(records)).toEqual({ kind: 'at', ms: ms('12:34:56.789') });
  });

  it('counts a meta prompt: every firing of a wake-up or a scheduled task is one', async () => {
    const fired = user('check the deploy', '12:43:00.000', { isMeta: true });
    expect(await activity([prompt('go'), assistant('end_turn'), fired])).toEqual({ kind: 'at', ms: ms('12:43:00.000') });
  });

  it('counts subagent records in the main transcript', async () => {
    const records = [prompt('go'), assistant('end_turn'), user('check a', '12:45:00.000', { isSidechain: true })];
    expect(await activity(records)).toEqual({ kind: 'at', ms: ms('12:45:00.000') });
  });

  it('is untimed when that record has no readable time', async () => {
    for (const timestamp of [undefined, null, 'yesterday', 12345, '']) {
      const last = { type: 'assistant', timestamp, message: { stop_reason: 'end_turn', content: [] } };
      expect(await activity([last]), String(timestamp)).toEqual({ kind: 'untimed' });
    }
  });

  it('is none when the whole file holds no such record', async () => {
    expect(await activity(modelCommand())).toEqual({ kind: 'none' });
    expect(await activity([noise('system'), noise('summary')])).toEqual({ kind: 'none' });
    expect((await readTurnReading(`${fx.dir}/missing.jsonl`)).activity).toEqual({ kind: 'none' });
  });

  it('is untimed when the window read does not reach back far enough to tell', async () => {
    const commands = Array.from({ length: 40 }, (_, i) => modelCommand(i % 10)).flat();
    const records = [prompt('go'), assistant('end_turn'), ...commands];
    const result = await reading(records, { ...MAIN, initialBytes: 512, limitBytes: 512 } as typeof MAIN);
    expect(result.turn).toMatchObject({ reason: 'localCommand' });
    expect(result.activity).toEqual({ kind: 'untimed' });
  });

  it('is untimed while a record is being written', async () => {
    const file = fx.write(`${jsonl([prompt('go'), assistant('end_turn')])}{"type":"user","mess`);
    expect(await readTurnReading(file, MAIN)).toEqual({
      turn: { state: 'OPEN', reason: 'recordBeingWritten', detail: null, scheduledWakeupSeconds: null },
      activity: { kind: 'untimed' },
      wakeupSeconds: null,
    });
  });
});

describe('a scheduled wake-up survives what is written while idle', () => {
  const loop = [
    prompt('/loop check the deploy'),
    wakeupCall({ delaySeconds: 600 }),
    toolResult('Wake-up scheduled.'),
    assistant('end_turn', [textBlock('Sleeping until the next check.')]),
  ];

  it('a local command after the turn', async () => {
    const result = await reading([...loop, ...modelCommand()]);
    expect(result.turn).toMatchObject({ reason: 'localCommand', scheduledWakeupSeconds: 600 });
    expect(result.wakeupSeconds).toBe(600);
  });

  it('an Esc after the turn', async () => {
    expect((await reading([...loop, marker()])).turn).toMatchObject({ reason: 'interrupted', scheduledWakeupSeconds: 600 });
  });

  it('a `!` line: the turn reads open, the wake-up is still reported', async () => {
    const result = await reading([...loop, user('<bash-input>ls</bash-input>', '12:42:00.000')]);
    expect(result.turn).toMatchObject({ state: 'OPEN', scheduledWakeupSeconds: null });
    expect(result.wakeupSeconds).toBe(600);
  });

  it('but not a new prompt', async () => {
    const result = await reading([...loop, user('stop looping', '12:50:00.000')]);
    expect(result.turn).toMatchObject({ state: 'OPEN', reason: 'thinking' });
    expect(result.wakeupSeconds).toBeNull();
  });

  it('nor a firing of the wake-up that ended without scheduling another', async () => {
    const fired = user('/loop check the deploy', '12:55:00.000', { isMeta: true });
    const lastRound = [fired, assistant('end_turn', [textBlock('Deploy is done; not checking again.')])];
    expect(await reading([...loop, ...lastRound])).toMatchObject({ turn: { scheduledWakeupSeconds: null }, wakeupSeconds: null });
    const stopped = [fired, wakeupCall({ stop: true }), toolResult('Stopped.'), assistant('end_turn')];
    expect((await reading([...loop, ...stopped])).wakeupSeconds).toBeNull();
    // Inside the final turn an Esc is not looked past either: the turn started at the firing.
    expect((await reading([...loop, fired, assistant('tool_use', [toolUse('Bash', {})]), marker()])).wakeupSeconds).toBeNull();
  });
});

describe('TurnCache.getReading', () => {
  it('caches the whole reading and hands every caller its own copy', async () => {
    const file = fx.transcript([prompt('go'), assistant('end_turn'), ...modelCommand()]);
    const { size, mtimeMs } = await import('node:fs').then((fs) => fs.statSync(file));
    const cache = new TurnCache();
    const first = await cache.getReading(file, size, mtimeMs, MAIN);
    expect(first.turn.reason).toBe('localCommand');
    first.activity = { kind: 'none' };
    first.turn.state = 'OPEN';
    const second = await cache.getReading(file, size, mtimeMs, MAIN);
    expect(second.activity).toEqual({ kind: 'at', ms: ms('12:34:56.789') });
    expect(second.turn.state).toBe('CLOSED');
    expect(await cache.get(file, size, mtimeMs, MAIN)).toEqual(second.turn);
  });
});
